Style/LineLength:
  Description: 'Limit lines to 130 characters.'
  Max: 130
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/RedundantBegin:
  Enabled: false
